Update docker_test.yml
Proposal for test docker compose on W11 and on Ubuntu

diff --git a/.github/workflows/docker_test.yml b/.github/workflows/docker_test.yml
--- a/.github/workflows/docker_test.yml
+++ b/.github/workflows/docker_test.yml
@@ -8,34 +8,46 @@ concurrency:
   cancel-in-progress: true
 jobs:
   test_docker:
-    name: Run test suite
-    runs-on: ubuntu-latest
+    name: Run test suite on ${{ matrix.os }}
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ubuntu-latest, windows-latest]
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
 
+    - name: Set up Docker
+      run: |
+        docker --version
+        docker-compose --version
+
     - name: Docker build
       run: |
         docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres
         TEST_SCRIPT=$(awk '/```docker-run.sh/{f=1;next} /```/{f=0} f' README.md)
-        echo $TEST_SCRIPT
+        echo "$TEST_SCRIPT"
         eval "$TEST_SCRIPT"
-    
+
     - name: Test docker run
       run: |
         sleep 15
         docker ps 
         pg_container_name=$(docker ps --format '{{.Names}}\t{{.Image}}' | grep 'prostgles' | head -1 | awk '{print $1}')
         echo $pg_container_name
-        eval "docker logs $pg_container_name"
-        curl -b -i -L  -v  localhost:3004 | grep -q "Prostgles UI"; echo $?
+        docker logs "$pg_container_name"
+        curl -b -i -L -v localhost:3004 | grep -q "Prostgles UI" && echo "Test passed" || echo "Test failed"
 
     - name: Docker stop
-      run: docker stop $(docker ps -a -q)
+      run: docker stop $(docker ps -a -q) || true
 
-    - name: Docker compose
-      run: docker compose up -d
+    - name: Docker compose up
+      run: |
+        docker compose up -d
 
     - name: Test docker compose
-      run: sleep 5 && docker ps && curl localhost:3004 | grep -q "Prostgles UI"; echo $?
+      run: |
+        sleep 5
+        docker ps
+        curl localhost:3004 | grep -q "Prostgles UI" && echo "Compose test passed" || echo "Compose test failed"
